/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HandTrackerJNI */

#ifndef _Included_HandTrackerJNI
#define _Included_HandTrackerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HandTrackerJNI
 * Method:    showRGB
 * Signature: (Ljava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_showRGB
  (JNIEnv *, jclass, jstring, jint, jbyteArray);

/*
 * Class:     HandTrackerJNI
 * Method:    showDepth
 * Signature: (Ljava/lang/String;I[S)V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_showDepth
  (JNIEnv *, jclass, jstring, jint, jshortArray);

/*
 * Class:     HandTrackerJNI
 * Method:    waitKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HandTrackerJNI_waitKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     HandTrackerJNI
 * Method:    getDefaultInitPos
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HandTrackerJNI_getDefaultInitPos
  (JNIEnv *, jclass);

/*
 * Class:     HandTrackerJNI
 * Method:    createHandTracker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_createHandTracker__
  (JNIEnv *, jobject);

/*
 * Class:     HandTrackerJNI
 * Method:    createHandTracker
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_createHandTracker__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     HandTrackerJNI
 * Method:    destroyHandTracker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_destroyHandTracker
  (JNIEnv *, jobject);

/*
 * Class:     HandTrackerJNI
 * Method:    grab
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_grab
  (JNIEnv *, jobject);

/*
 * Class:     HandTrackerJNI
 * Method:    setCamera
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_setCamera
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     HandTrackerJNI
 * Method:    computeBoundingBox
 * Signature: ([DF)V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_computeBoundingBox
  (JNIEnv *, jobject, jdoubleArray, jfloat);

/*
 * Class:     HandTrackerJNI
 * Method:    zoomVirtualCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_zoomVirtualCamera
  (JNIEnv *, jobject);

/*
 * Class:     HandTrackerJNI
 * Method:    preprocessInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_preprocessInput
  (JNIEnv *, jobject);

/*
 * Class:     HandTrackerJNI
 * Method:    uploadObservations
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_uploadObservations
  (JNIEnv *, jobject);

/*
 * Class:     HandTrackerJNI
 * Method:    track
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_HandTrackerJNI_track
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     HandTrackerJNI
 * Method:    visualize
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_HandTrackerJNI_visualize
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
